Rewrite documentation
dice-group/IGUANA pull request #233
Opened 2023-11-07 11:58 UTC by nck-mlcnv

- [ ] Write the markdown documentation
- [ ] Copy it to the wiki
- [ ] Update the owl file

2024-03-27 10:10 UTC, bigerl requested changes
thx for the PR. Looks good and almost done. 
Please find my suggestions and comments below.

2024-03-27 10:10 UTC, bigerl commented on docs_new/introduction.md
> +# IGUANA
try to keep duplication as minimal as possible. Ideally this says them same as the README.md

In that case, it should be a symlink to README.md not a copy.

2024-03-27 10:10 UTC, bigerl commented on example-suite.yml
>  datasets:
```suggestion
# This file showcases the configuration of most IGUANA features.

datasets:
```

2024-03-27 10:10 UTC, bigerl commented on schema/iguana.owl
> +        <rdfs:label>NoQ Metric</rdfs:label>
labels are wrong

2024-03-28 10:43 UTC, nck-mlcnv commented on docs_new/configuration/metrics.md
> +Queries per second.
I've switched to a table.

2024-06-06 07:48 UTC, bigerl approved these changes
Looks good now. Thx for the work 👍🏻

2024-06-10 14:47 UTC, merged